name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run main file
        run: go run main.go 

      - name: ping api
        run : curl localhost:8080/ping  

      - name: Run car folders main file
        run: go run car/car.go     
